version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t yogiy31/react-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push yogiy31/react-app:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            git clone https://github.com/yyogendra31/Project1.1kubernetes.git
            git config --global user.email "yadavyogendra31@gmail.com"
            git config --global user.name "yyogendra31"
            pwd
            cd Project1.1kubernetes
            pwd
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" deployment/react-deployment.yaml
            cat deployment/react-deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config --global credential.helper cache
            git push -q https://github.com/yyogendra31/Project1.1kubernetes.git main
workflows:
  Yogireactflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push
